apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kserve-download-model
spec:
  description: This Task can be used to a download a model
  params:
  - name: model-name
    type: string
  - name: model-relative-path
    type: string
    default: ""
  - name: current-namespace
    default: "default"
    type: string
  - name: s3-bucket-name
    type: string
  results:
  - name: s3-url
    description: The S3 URL used to download the model
  steps:
  - name: download-model-s3
    image: quay.io/opendatahub/kserve-storage-initializer:v0.11.1.3
    script: |
      WORKSPACE_DIR="$(workspaces.workspace.path)/model_dir-$(params.model-name)"

      # This if statement is required because boto3 does not translate a `//` to a `/`
      # when used inside a path similar to bash
      if [ -n "$(params.model-relative-path)" ]; then
        S3_URL="s3://$(params.s3-bucket-name)/$(params.model-relative-path)/$(params.model-name)"
        # Include the model-relative-path in the local workspace directory to align with the
        #  expectations when the model is fetched from a git repository where the relative path
        #  is required
        MODEL_DIR="$WORKSPACE_DIR/$(params.model-relative-path)/$(params.model-name)"
      else
        MODEL_DIR="$WORKSPACE_DIR/$(params.model-name)"
        S3_URL="s3://$(params.s3-bucket-name)/$(params.model-name)"
      fi

      mkdir -p $MODEL_DIR

      echo -n $S3_URL | tee $(results.s3-url.path) ;

      if [ -n "$(workspaces.ssl-ca-directory.path)" ]; then
        export CA_BUNDLE_CONFIGMAP_NAME=ssl-ca-directory
        export AWS_CA_BUNDLE=$(workspaces.ssl-ca-directory.path)/ca-bundle.crt
      fi
      
      STORAGE_CONFIG="$(cat $(workspaces.s3-secret.path)/s3-storage-config)" /storage-initializer/scripts/initializer-entrypoint \
      $S3_URL $MODEL_DIR
  workspaces:
  - description: The workspace for the downloaded model.
    name: workspace
  - description: The S3 secret.
    name: s3-secret
  - description: |
      A workspace containing CA certificates, this will be used by the model download script to
      verify the peer with when fetching over HTTPS.
    name: ssl-ca-directory
    optional: true
